# Generated by Django 4.2 on 2023-04-09 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BA_Accounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.TextField(blank=True, null=True, unique=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'ba_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BA_Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ba_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DS_Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ds_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DS_Prescriptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ds_prescriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DS_Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(blank=True, null=True, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ds_storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DS_Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ds_suppliers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GY_Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('membership_start', models.DateField(blank=True, null=True)),
                ('membership_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gy_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GY_Shifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('workhours', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gy_shifts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GY_Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'gy_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PR_Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('denomination', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pr_prayer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RE_Apartments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('apartment_number', models.IntegerField(blank=True, null=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('occupied', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_apartments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RE_Houses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True, unique=True)),
                ('number_of_rooms', models.IntegerField(blank=True, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('occupied', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_houses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RE_Residents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('family_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('religion', models.TextField(blank=True, null=True)),
                ('property_type', models.TextField(blank=True, null=True)),
                ('propertyid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 're_residents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'sc_enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_LibraryBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
                ('isbn', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_library_books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_LibraryLoans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('borrowed_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_library_loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_LibraryMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_library_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_students',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SC_Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sc_teachers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SM_Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'sm_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SM_Functions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('workload', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_functions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SM_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('kosher', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SM_Shifts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('workhours', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sm_shifts',
                'managed': False,
            },
        ),
    ]
